version: '3.5'

services:
  # build the docker image for the web application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: librishop
    container_name: librishop-web
    environment:
      DB_HOST: "mariadb"
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
  # standard mariadb docker image
  mariadb:
    image: mariadb
    container_name: librishop-db
    environment:
      MYSQL_ROOT_PASSWORD: "pizza"
      MYSQL_USER: "tsw"
      MYSQL_PASSWORD: "biscotto"
      MYSQL_DATABASE: "base"
    ports:
      - "3306:3306"
    volumes:
      - "./db/tabelle.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./db/insert.sql:/docker-entrypoint-initdb.d/2.sql"
    # script to check if innodb is initialized before starting container
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10